apiVersion: v1
kind: Service
metadata:
  labels:
    app: private-registry
  name: private-registry
spec:
  ports:
  - port: 5000
    nodePort: {{ registry_nodeport }}
    protocol: TCP
    targetPort: 5000
  selector:
    app: private-registry
  type: NodePort
